services:
  reverse-proxy:
    image: traefik:v3.1.0
    command:
      - --providers.docker
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik
      - /etc/traefik/certs:/etc/traefik/certs
    networks:
      - traefik
networks:
  traefik:
    external: true